# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM node:lts-alpine
WORKDIR /app

# Copy package files and install dependencies
COPY package.json package-lock.json* ./
RUN npm install --production

# Copy all source files
COPY src ./src

# Patch analytics.js to remove shebang and require
RUN sed -i '/^#!.*$/d' src/analytics.js \
    && sed -i "1i import crypto from 'crypto';" src/analytics.js \
    && sed -i "2i import os from 'os';" src/analytics.js \
    && sed -i "s|const crypto = require('crypto');||g" src/analytics.js \
    && sed -i "s|const os = require('os');||g" src/analytics.js

# Ensure executable permission
RUN chmod +x src/mcp-server.js

# Use stdio transport entrypoint
CMD ["node","src/mcp-server.js"]
